### ISSUE TITLE
Get current input source failed

### ISSUE THREAD

**Issue by heronghua** [rieonke/idea-auto-switch-im#8]

**Comment by lovepocky** [comment]
```

2018-12-14 23:17:57,577 [467879085]  ERROR - oSwitchIm.util.InputSourceUtil - Current Command:  
2018-12-14 23:17:57,578 [467879086]   INFO - .component.AutoSwitchComponent - CURRENT INPUT SOURCE   
2018-12-14 23:17:57,590 [467879098]   INFO - .component.AutoSwitchComponent - GET CURRENT INPUT SOURCE FAILED 
2018-12-14 23:17:57,595 [467879103]  ERROR - oSwitchIm.util.InputSourceUtil - Current Command:  
2018-12-14 23:17:57,597 [467879105]   INFO - .component.AutoSwitchComponent - Current Command Name is  
2018-12-14 23:17:57,597 [467879105]   INFO - oSwitchIm.util.InputSourceUtil - GET CURRENT INPUT SOURCE 
	at cn.rieon.idea.plugin.AutoSwitchIm.util.InputSourceUtil.nativeGetCurrentInputSource(InputSourceUtil.kt:56)
	at cn.rieon.idea.plugin.AutoSwitchIm.util.InputSourceUtil.getCurrentInputSource(InputSourceUtil.kt:107)
	at cn.rieon.idea.plugin.AutoSwitchIm.component.AutoSwitchComponent.getCurrentInputSourceId(AutoSwitchComponent.kt:158)
2018-12-14 23:17:57,603 [467879111]  ERROR - oSwitchIm.util.InputSourceUtil - Current Command:  
2018-12-14 23:17:57,604 [467879112]   INFO - .component.AutoSwitchComponent - CURRENT INPUT SOURCE   
2018-12-14 23:17:57,619 [467879127]   INFO - .component.AutoSwitchComponent - GET CURRENT INPUT SOURCE FAILED 
2018-12-14 23:17:57,625 [467879133]  ERROR - oSwitchIm.util.InputSourceUtil - Current Command:  
2018-12-14 23:17:57,700 [467879208]   INFO - .component.AutoSwitchComponent - Current Command Name is  
2018-12-14 23:17:57,700 [467879208]   INFO - oSwitchIm.util.InputSourceUtil - GET CURRENT INPUT SOURCE 
	at cn.rieon.idea.plugin.AutoSwitchIm.util.InputSourceUtil.nativeGetCurrentInputSource(InputSourceUtil.kt:56)
	at cn.rieon.idea.plugin.AutoSwitchIm.util.InputSourceUtil.getCurrentInputSource(InputSourceUtil.kt:107)
	at cn.rieon.idea.plugin.AutoSwitchIm.component.AutoSwitchComponent.getCurrentInputSourceId(AutoSwitchComponent.kt:158)
2018-12-14 23:17:57,706 [467879214]  ERROR - oSwitchIm.util.InputSourceUtil - Current Command:  
2018-12-14 23:17:57,707 [467879215]   INFO - .component.AutoSwitchComponent - CURRENT INPUT SOURCE   
2018-12-14 23:17:57,720 [467879228]   INFO - .component.AutoSwitchComponent - GET CURRENT INPUT SOURCE FAILED 
2018-12-14 23:17:57,724 [467879232]  ERROR - oSwitchIm.util.InputSourceUtil - Current Command:  
2018-12-14 23:17:57,726 [467879234]   INFO - .component.AutoSwitchComponent - Current Command Name is  
2018-12-14 23:17:57,726 [467879234]   INFO - oSwitchIm.util.InputSourceUtil - GET CURRENT INPUT SOURCE 
	at cn.rieon.idea.plugin.AutoSwitchIm.util.InputSourceUtil.nativeGetCurrentInputSource(InputSourceUtil.kt:56)
	at cn.rieon.idea.plugin.AutoSwitchIm.util.InputSourceUtil.getCurrentInputSource(InputSourceUtil.kt:107)
	at cn.rieon.idea.plugin.AutoSwitchIm.component.AutoSwitchComponent.getCurrentInputSourceId(AutoSwitchComponent.kt:158)
2018-12-14 23:17:57,731 [467879239]  ERROR - oSwitchIm.util.InputSourceUtil - Current Command:  
2018-12-14 23:17:57,732 [467879240]   INFO - .component.AutoSwitchComponent - CURRENT INPUT SOURCE   
2018-12-14 23:17:57,744 [467879252]   INFO - .component.AutoSwitchComponent - GET CURRENT INPUT SOURCE FAILED 
2018-12-14 23:17:57,748 [467879256]  ERROR - oSwitchIm.util.InputSourceUtil - Current Command:  
2018-12-14 23:17:57,808 [467879316]   INFO - .component.AutoSwitchComponent - Current Command Name is  
2018-12-14 23:17:57,808 [467879316]   INFO - oSwitchIm.util.InputSourceUtil - GET CURRENT INPUT SOURCE 
	at cn.rieon.idea.plugin.AutoSwitchIm.util.InputSourceUtil.nativeGetCurrentInputSource(InputSourceUtil.kt:56)
	at cn.rieon.idea.plugin.AutoSwitchIm.util.InputSourceUtil.getCurrentInputSource(InputSourceUtil.kt:107)
	at cn.rieon.idea.plugin.AutoSwitchIm.component.AutoSwitchComponent.getCurrentInputSourceId(AutoSwitchComponent.kt:158)
2018-12-14 23:17:57,814 [467879322]  ERROR - oSwitchIm.util.InputSourceUtil - Current Command:  
2018-12-14 23:17:57,814 [467879322]   INFO - .component.AutoSwitchComponent - CURRENT INPUT SOURCE   
2018-12-14 23:17:57,827 [467879335]   INFO - .component.AutoSwitchComponent - GET CURRENT INPUT SOURCE FAILED 
2018-12-14 23:17:57,832 [467879340]  ERROR - oSwitchIm.util.InputSourceUtil - Current Command:  
2018-12-14 23:17:57,834 [467879342]   INFO - .component.AutoSwitchComponent - Current Command Name is  
2018-12-14 23:17:57,834 [467879342]   INFO - oSwitchIm.util.InputSourceUtil - GET CURRENT INPUT SOURCE 
	at cn.rieon.idea.plugin.AutoSwitchIm.util.InputSourceUtil.nativeGetCurrentInputSource(InputSourceUtil.kt:56)
	at cn.rieon.idea.plugin.AutoSwitchIm.util.InputSourceUtil.getCurrentInputSource(InputSourceUtil.kt:107)
```


```
2018-12-14 23:17:58,536 [467880044]  ERROR - oSwitchIm.util.InputSourceUtil - IntelliJ IDEA 2018.2.2  Build #IU-182.4129.33 
2018-12-14 23:17:58,536 [467880044]  ERROR - oSwitchIm.util.InputSourceUtil - JDK: 1.8.0_152-release 
2018-12-14 23:17:58,536 [467880044]  ERROR - oSwitchIm.util.InputSourceUtil - VM: OpenJDK 64-Bit Server VM 
2018-12-14 23:17:58,536 [467880044]  ERROR - oSwitchIm.util.InputSourceUtil - Vendor: JetBrains s.r.o 
2018-12-14 23:17:58,536 [467880044]  ERROR - oSwitchIm.util.InputSourceUtil - OS: Mac OS X 
2018-12-14 23:17:58,536 [467880044]  ERROR - oSwitchIm.util.InputSourceUtil - Last Action: SaveAll 
2018-12-14 23:17:58,536 [467880044]  ERROR - oSwitchIm.util.InputSourceUtil - Current Command:  
2018-12-14 23:17:58,536 [467880044]   INFO - .component.AutoSwitchComponent - CURRENT INPUT SOURCE   
2018-12-14 23:17:58,544 [467880052]   INFO - .component.AutoSwitchComponent - GET CURRENT INPUT SOURCE FAILED 
2018-12-14 23:17:58,544 [467880052]   INFO - .component.AutoSwitchComponent - SWITCH TO INPUT SOURCE  com.apple.keylayout.US 
2018-12-14 23:17:58,544 [467880052]   INFO - oSwitchIm.util.InputSourceUtil - SWITCH TO INPUT SOURCE com.apple.keylayout.US 
2018-12-14 23:17:58,544 [467880052]   INFO - oSwitchIm.util.InputSourceUtil - EXEC COMMAND /var/folders/w2/dndy1lwn3yg4w33jrwy6nkv00000gn/T/ImSelect8502750639572195516.tmp -s com.apple.keylayout.US 
2018-12-14 23:17:58,547 [467880055]  ERROR - oSwitchIm.util.InputSourceUtil - EXEC FAILED! 
java.lang.Throwable: EXEC FAILED!
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:123)
	at cn.rieon.idea.plugin.AutoSwitchIm.util.InputSourceUtil.execImSelect$IdeaAutoSwitchIm_main(InputSourceUtil.kt:88)
	at cn.rieon.idea.plugin.AutoSwitchIm.util.InputSourceUtil.nativeSwitchToInputSource(InputSourceUtil.kt:63)
	at cn.rieon.idea.plugin.AutoSwitchIm.util.InputSourceUtil.switchTo(InputSourceUtil.kt:112)
	at cn.rieon.idea.plugin.AutoSwitchIm.component.AutoSwitchComponent.switchTo$IdeaAutoSwitchIm_main(AutoSwitchComponent.kt:174)
	at cn.rieon.idea.plugin.AutoSwitchIm.component.AutoSwitchComponent.handle$IdeaAutoSwitchIm_main(AutoSwitchComponent.kt:307)
	at cn.rieon.idea.plugin.AutoSwitchIm.component.AutoSwitchComponent.handleOutVimInsertSwitch$IdeaAutoSwitchIm_main(AutoSwitchComponent.kt:259)
	at cn.rieon.idea.plugin.AutoSwitchIm.component.AutoSwitchComponent$commandListener$1.beforeCommandFinished(AutoSwitchComponent.kt:130)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.fireCommandFinished(CoreCommandProcessor.java:197)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.finishCommand(CoreCommandProcessor.java:181)
	at com.intellij.openapi.command.impl.CommandProcessorImpl.finishCommand(CommandProcessorImpl.java:32)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:145)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:97)
	at com.intellij.openapi.editor.impl.EditorImpl$MyInputMethodHandler.lambda$runUndoTransparent$1(EditorImpl.java:3495)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.runUndoTransparentAction(CoreCommandProcessor.java:321)
	at com.intellij.openapi.editor.impl.EditorImpl$MyInputMethodHandler.runUndoTransparent(EditorImpl.java:3494)
	at com.intellij.openapi.editor.impl.EditorImpl$MyInputMethodHandler.replaceInputMethodText(EditorImpl.java:3523)
	at com.intellij.openapi.editor.impl.EditorImpl$MyInputMethodHandler.access$7900(EditorImpl.java:3340)
	at com.intellij.openapi.editor.impl.EditorImpl.replaceInputMethodText(EditorImpl.java:3210)
	at com.intellij.openapi.editor.impl.EditorComponentImpl.processInputMethodEvent(EditorComponentImpl.java:188)
	at java.awt.Component.processEvent(Component.java:6330)
	at java.awt.Container.processEvent(Container.java:2237)
	at java.awt.Component.dispatchEventImpl(Component.java:4903)
	at java.awt.Container.dispatchEventImpl(Container.java:2295)
	at java.awt.Component.dispatchEvent(Component.java:4725)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:737)
	at java.awt.EventQueue$4.run(EventQueue.java:735)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:781)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:722)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```
